name: Run tests in all Maven subprojects

on: [push, pull_request]

jobs:
  test-all-projects:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests in all subprojects
      shell: bash
      run: |
        for dir in */; do
          if [ -f "$dir/pom.xml" ]; then
            echo "📦 Running tests in $dir"
            mvn -f "$dir/pom.xml" test || exit 1
          fi
        done
